#%RAML 1.0 Trait
usage: Apply this trait to ensure user maintain tranaction header
headers:
  x-transaction-id:
    type: string
    required: false
    description: Transaction id maintains over the API's