#%RAML 1.0 Trait
usage: Enable consumers to add thier own correalation id
headers:
  x-correlation-id:
    type: string
    required: false
    description: correalation id maintains over all API's